parameters:
services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    App\DataProcessing\DataSourceOrigin:
        arguments:
            - '@App\DataProcessing\DataFromAlpha'
            - '@App\DataProcessing\DataFromWTG'
    App\DataProcessing\RefactoringProcess:
        arguments:
            - '@App\DataProcessing\RefactoredAlphaData'
            - '@App\DataProcessing\RefactoredWTGData'        

    App\Controller\DataController:
        bind: 
            $dataRetrieval: '@App\DataProcessing\DataSourceOrigin'
            $dataRefactoring: '@App\DataProcessing\RefactoringProcess'

    
    



    
            
